apiVersion: v1
kind: Service
metadata:
  name: inquiries-service
spec:
  selector:
    app: inquiries
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquiries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inquiries
  template:
    metadata:
      labels:
        app: inquiries
    spec:
      containers:
        - name: inquiries
          image: ticketflow/inquiries:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: Postgres__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: inquiries-connection-string
            - name: rabbitMq__hostName
              value: "rabbitmq-service"
            - name: Services__Tickets__Url
              value: "http://tickets-service"
            - name: Services__Translations__Url
              value: "http://translations-service"
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "1.5Gi"
              cpu: "500m"
