apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigateway
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: ticketflow/apigateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ReverseProxy__Clusters__inquiries__Destinations__destination1__Address
              value: "http://inquiries-service"
            - name: ReverseProxy__Clusters__tickets__Destinations__destination1__Address
              value: "http://tickets-service"
            - name: ReverseProxy__Clusters__communication__Destinations__destination1__Address
              value: "http://communication-service"
            - name: ReverseProxy__Clusters__system-metrics__Destinations__destination1__Address
              value: "http://systemmetrics-service"
