apiVersion: v1
kind: Service
metadata:
  name: personalinfovault-service
spec:
  selector:
    app: personalinfovault
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personalinfovault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personalinfovault
  template:
    metadata:
      labels:
        app: personalinfovault
    spec:
      containers:
        - name: personalinfovault
          image: ticketflow/personalinfovault:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: Postgres__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: personalinfovault-connection-string
            - name: rabbitMq__hostName
              value: "rabbitmq-service"
