apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  postgres-password: "postgres"
  tickets-connection-string: "Host=postgres-service;Database=TicketFlow.Tickets;Username=postgres;Password=postgres"
  inquiries-connection-string: "Host=postgres-service;Database=TicketFlow.Inquiries;Username=postgres;Password=postgres"
  personalinfovault-connection-string: "Host=postgres-service;Database=TicketFlow.PersonalInfoVault;Username=postgres;Password=postgres"
