apiVersion: v1
kind: Service
metadata:
  name: translations-service
spec:
  selector:
    app: translations
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translations
spec:
  replicas: 2
  selector:
    matchLabels:
      app: translations
  template:
    metadata:
      labels:
        app: translations
    spec:
      containers:
        - name: translations
          image: ticketflow/translations:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: rabbitMq__hostName
              value: "rabbitmq-service"
          