FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src
COPY ["src/Services/Translations/TicketFlow.Services.Translations.Api/TicketFlow.Services.Translations.Api.csproj", "src/Services/Translations/TicketFlow.Services.Translations.Api/"]
COPY ["src/Services/Translations/TicketFlow.Services.Translations.Core/TicketFlow.Services.Translations.Core.csproj", "src/Services/Translations/TicketFlow.Services.Translations.Core/"]
COPY ["src/Shared/TicketFlow.Shared/TicketFlow.Shared.csproj", "src/Shared/TicketFlow.Shared/"]
COPY ["src/Shared/TicketFlow.Shared.Contracts/TicketFlow.Shared.Contracts.csproj", "src/Shared/TicketFlow.Shared.Contracts/"]
COPY ["src/Shared/TicketFlow.CourseUtils/TicketFlow.CourseUtils.csproj", "src/Shared/TicketFlow.CourseUtils/"]
COPY ["src/Services/SystemMetrics/TicketFlow.Services.SystemMetrics.Generator/TicketFlow.Services.SystemMetrics.Generator.csproj", "src/Services/SystemMetrics/TicketFlow.Services.SystemMetrics.Generator/"]
RUN dotnet restore "src/Services/Translations/TicketFlow.Services.Translations.Api/TicketFlow.Services.Translations.Api.csproj"
COPY . .
WORKDIR "/src/src/Services/Translations/TicketFlow.Services.Translations.Api"
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TicketFlow.Services.Translations.Api.dll"]
