// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketFlow.Services.Anonymization.Core.Data;

#nullable disable

namespace TicketFlow.Services.Anonymization.Core.Migrations
{
    [DbContext(typeof(AnonymizationDbContext))]
    partial class AnonymizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketFlow.Services.Anonymization.Core.Data.Models.AnonymizationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PersonToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestedByEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PersonToken");

                    b.HasIndex("Status");

                    b.ToTable("AnonymizationRequests");
                });

            modelBuilder.Entity("TicketFlow.Services.Anonymization.Core.Data.Models.ServiceAnonymizationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnonymizationRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AnonymizationRequestId");

                    b.ToTable("ServiceStatuses");
                });

            modelBuilder.Entity("TicketFlow.Services.Anonymization.Core.Data.Models.ServiceAnonymizationStatus", b =>
                {
                    b.HasOne("TicketFlow.Services.Anonymization.Core.Data.Models.AnonymizationRequest", "AnonymizationRequest")
                        .WithMany("ServiceStatuses")
                        .HasForeignKey("AnonymizationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnonymizationRequest");
                });

            modelBuilder.Entity("TicketFlow.Services.Anonymization.Core.Data.Models.AnonymizationRequest", b =>
                {
                    b.Navigation("ServiceStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
